/* milter-ahead.h.  Generated by configure.  */

/***********************************************************************
 ***
 ***********************************************************************/

#define MILTER_NAME "milter-ahead"
#define MILTER_MAJOR 0
#define MILTER_MINOR 4
/* #undef MILTER_BUILD */
#define MILTER_AUTHOR "Anthony Howe <achowe@snert.com>"
#define MILTER_VERSION "milter-ahead/0.4." MILTER_BUILD_STRING
#define MILTER_COPYRIGHT "Copyright 2004 by Anthony Howe. All rights reserved."

#define STATEDIR "/var/milter-ahead"
#define RUN_AS_USER "smmsp"
#define RUN_AS_GROUP "smmsp"
/* #undef CACHE_TYPE */

#define SMTP_PORT 25

#define HAVE_GETHOSTNAME 1
#define HAVE_GETHOSTBYNAME 1
/* #undef HAVE_GETHOSTBYNAME2 */

#define MILTER_WITH_BERKELEY_DB 1

/***********************************************************************
 *** END
 ***********************************************************************/
